export const authSagaActionTypes = {
  LOGIN_SAGA: "LOGIN_SAGA",
  RESET_PASSWORD_SAGA: "RESET_PASSWORD_SAGA",
  CHANGE_PASSWORD_SAGA: "CHANGE_PASSWORD_SAGA",
};

export const genreSagaActionTypes = {
  GET_GENRES_SAGA: "GET_GENRES_SAGA",
  ADD_GENRE_SAGA: "ADD_GENRE_SAGA",
  UPDATE_GENRE_SAGA: "UPDATE_GENRE_SAGA",
  DELETE_GENRE_SAGA: "DELETE_GENRE_SAGA",
};

export const snackSagaActionTypes = {
  GET_SNACKS_SAGA: "GET_SNACKS_SAGA",
  ADD_SNACK_SAGA: "ADD_SNACK_SAGA",
  UPDATE_SNACK_SAGA: "UPDATE_SNACK_SAGA",
  DELETE_SNACK_SAGA: "DELETE_SNACK_SAGA",
};

export const actorSagaActionTypes = {
  GET_ACTORS_SAGA: "GET_ACTORS_SAGA",
  ADD_ACTOR_SAGA: "ADD_ACTOR_SAGA",
  UPDATE_ACTOR_SAGA: "UPDATE_ACTOR_SAGA",
  DELETE_ACTOR_SAGA: "DELETE_ACTOR_SAGA",
};

export const imageSagaActionTypes = {
  POST_IMAGE_SAGA: "POST_IMAGE_SAGA",
};
