export const authSagaActionTypes = {
  LOGIN_SAGA: "LOGIN_SAGA",
  RESET_PASSWORD_SAGA: "RESET_PASSWORD_SAGA",
  CHANGE_PASSWORD_SAGA: "CHANGE_PASSWORD_SAGA",
};

export const genreSagaActionTypes = {
  GET_GENRES_SAGA: "GET_GENRES_SAGA",
  ADD_GENRE_SAGA: "ADD_GENRE_SAGA",
  UPDATE_GENRE_SAGA: "UPDATE_GENRE_SAGA",
  DELETE_GENRE_SAGA: "DELETE_GENRE_SAGA",
};

export const snackSagaActionTypes = {
  GET_SNACKS_SAGA: "GET_SNACKS_SAGA",
  ADD_SNACK_SAGA: "ADD_SNACK_SAGA",
  UPDATE_SNACK_SAGA: "UPDATE_SNACK_SAGA",
  DELETE_SNACK_SAGA: "DELETE_SNACK_SAGA",
};

export const actorSagaActionTypes = {
  GET_ACTORS_SAGA: "GET_ACTORS_SAGA",
  ADD_ACTOR_SAGA: "ADD_ACTOR_SAGA",
  UPDATE_ACTOR_SAGA: "UPDATE_ACTOR_SAGA",
  DELETE_ACTOR_SAGA: "DELETE_ACTOR_SAGA",
};

export const roomTypeSagaActionTypes = {
  GET_ROOM_TYPES_SAGA: "GET_ROOM_TYPES_SAGA",
  ADD_ROOM_TYPE_SAGA: "ADD_ROOM_TYPE_SAGA",
  UPDATE_ROOM_TYPE_SAGA: "UPDATE_ROOM_TYPE_SAGA",
  DELETE_ROOM_TYPE_SAGA: "DELETE_ROOM_TYPE_SAGA",
};

export const movieSagaActionTypes = {
  GET_MOVIES_SAGA: "GET_MOVIES_SAGA",
  ADD_MOVIE_SAGA: "ADD_MOVIE_SAGA",
  UPDATE_MOVIE_SAGA: "UPDATE_MOVIE_SAGA",
  DELETE_MOVIE_SAGA: "DELETE_MOVIE_SAGA",
  GET_DATA_FOR_MOVIE: "GET_DATA_FOR_MOVIE",
};

export const staffSagaActionTypes = {
  GET_STAFFS_SAGA: "GET_STAFFS_SAGA",
  ADD_STAFF_SAGA: "ADD_STAFF_SAGA",
  UPDATE_STAFF_SAGA: "UPDATE_STAFF_SAGA",
  DELETE_STAFF_SAGA: "DELETE_STAFF_SAGA",
};

export const postSagaActionTypes = {
  GET_ALL_POSTS_SAGA: "GET_ALL_POSTS_SAGA",
  GET_MY_POSTS_SAGA: "GET_MY_POSTS_SAGA",
  ADD_POST_SAGA: "ADD_POST_SAGA",
  UPDATE_POST_SAGA: "UPDATE_POST_SAGA",
  DELETE_POST_SAGA: "DELETE_POST_SAGA",
};

export const roomSagaActionTypes = {
  GET_ROOMS_SAGA: "GET_ROOMS_SAGA",
  GET_ROOM_BY_ID_SAGA: "GET_ROOM_BY_ID_SAGA",
  ADD_ROOM_SAGA: "ADD_ROOM_SAGA",
  UPDATE_ROOM_SAGA: "UPDATE_ROOM_SAGA",
  DELETE_ROOM_SAGA: "DELETE_ROOM_SAGA",
  GET_DATA_FOR_ROOM: "GET_DATA_FOR_ROOM",
};

export const showTimeSagaActionTypes = {
  GET_SHOW_TIMES_BY_DATE_SAGA: "GET_SHOW_TIMES_BY_DATE_SAGA",
  ADD_SHOW_TIME_SAGA: "ADD_SHOW_TIME_SAGA",
  UPDATE_SHOW_TIME_SAGA: "UPDATE_SHOW_TIME_SAGA",
  DELETE_SHOW_TIME_SAGA: "DELETE_SHOW_TIME_SAGA",
  GET_DATA_FOR_SHOW_TIME: "GET_DATA_FOR_SHOW_TIME",
};

export const transactionSagaActionTypes = {
  GET_TRANSACTIONS_SAGA: "GET_TRANSACTIONS_SAGA",
  ADD_TRANSACTION_SAGA: "ADD_TRANSACTION_SAGA",
  GET_DATA_FOR_TRANSACTION: "GET_DATA_FOR_TRANSACTION",
};

export const imageSagaActionTypes = {
  POST_IMAGE_SAGA: "POST_IMAGE_SAGA",
};
